---
- name: Install nginx package
  yum: name=nginx state=present
  notify:
  - start nginx
  - sys start nginx

#- name: start nginx
#  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'
 
#- name: sys start nginx 
#  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: Enable "nginx" service on boot
  service: name=nginx enabled=yes
